Repository DistributedCollective/governance-dapp, pull requests merged in 2021-07, with the labels that each got.

#121 Proposals not loading
  package.json
  src/app/components/ProposalListItem/index.tsx
  src/app/components/VoteProgress/index.tsx
  src/app/containers/BlockChainProvider/abi/multicall.json
  src/app/containers/BlockChainProvider/contracts.ts
  src/app/containers/BlockChainProvider/types.ts
  src/app/containers/HomePage/index.tsx
  src/app/containers/ProposalDetailsPage/components/VoteCaster.tsx
  src/app/containers/ProposalDetailsPage/index.tsx
  src/app/containers/ProposalRow/index.tsx
  src/app/hooks/useProposalList.ts
  src/types/Proposal.ts
  src/utils/helpers.ts
  yarn.lock
Labels: enhancement

#124 Load proposal data as soon as possible (#123)
  src/app/containers/ProposalDetailsPage/index.tsx
Labels: release

#125 Fix proposal vote loading
  src/app/containers/ProposalDetailsPage/index.tsx
Labels: bug

#126 Fix proposal vote loading (#125)
  src/app/containers/ProposalDetailsPage/index.tsx
Labels: bug

#129 Update logo (#128)
  public/index.html
  src/app/components/Header/index.tsx
  src/assets/images/sovryn-logo-alpha.svg
Labels: enhancement
