Repository DistributedCollective/governance-dapp, pull requests merged in 2021-04, with the labels that each got.

#76 Release
  package.json
  src/app/containers/ProposalDetailsPage/components/VoteCaster.tsx
  src/app/containers/ProposalDetailsPage/index.tsx
  src/app/containers/StakePage/components/HistoryEventsTable.tsx
  src/app/containers/StakePage/components/VestingContract.tsx
  src/app/containers/StakePage/index.tsx
  src/styles/tailwind.css
Labels: release

#71 add propose page.
  src/app/components/CustomDialog/index.tsx
  src/app/containers/BlockChainProvider/requests/governance.ts
  src/app/containers/HomePage/index.tsx
  src/app/containers/ProposePage/Loadable.tsx
  src/app/containers/ProposePage/index.tsx
  src/app/index.tsx
Labels: enhancement

#75 Feat/25 interface queuing proposals
  src/app/containers/BlockChainProvider/requests/governance.ts
  src/app/containers/ProposalDetailsPage/components/VoteCaster.tsx
  src/app/containers/ProposalDetailsPage/index.tsx
Labels: enhancement

#82 add fix #78
  src/app/containers/StakePage/index.tsx
Labels: bug

#70 added new wallet library
  README.md
  package.json
  src/app/components/VestingDelegationDialog/index.tsx
  src/app/containers/BlockChainProvider/classifiers.ts
  src/app/containers/BlockChainProvider/components/WalletConnectorButton/index.tsx
  src/app/containers/BlockChainProvider/index.tsx
  src/app/containers/BlockChainProvider/network.ts
  src/app/containers/BlockChainProvider/saga.ts
  src/app/containers/BlockChainProvider/slice.ts
  src/app/containers/BlockChainProvider/types.ts
  src/app/containers/BlockChainProvider/web3-modal.ts
  src/app/hooks/staking/useStaking_computeWeightByDate.ts
  src/app/hooks/useAccount.ts
  src/app/hooks/useIsConnected.ts
  src/index.tsx
  src/styles/tailwind.css
  vercel.json
  yarn.lock
Labels: enhancement

#98 fix dialog issues.
  src/app/components/CustomDialog/index.tsx
  src/app/containers/ProposalsPage/index.tsx
  src/styles/sass/_genesis-sale.scss
Labels: bug
